resolver: lts-16.22
allow-newer: true
extra-deps:
- mu-schema-0.3.1.1
- mu-rpc-0.4.0.1
- mu-graphql-0.4.1.0
- graphql-0.11.0.0
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- stm-lifted-2.5.0.0
